from pathlib import Path
import re
p=Path('index.html')
s=p.read_text()
enroll="""async function enroll(uid){const u=D.u.find(x=>x.id===uid);const current=D.e.filter(x=>x.user_id===uid&&x.activa);modal('<h2>Actividades de '+esc(u.nombre)+'</h2><p class=\"muted\">Selecciona las actividades en las que está apuntado/a.</p><div id=\"eb\">'+D.a.filter(x=>x.activa).map(a=>{const e=current.find(z=>z.activity_id===a.id);const n=a.nombre.trim().toLowerCase();const club=n==='club de ocio',ceas=n==='ceas';return '<div class=\"card\" style=\"margin:6px 0\"><label style=\"margin:0\"><input type=\"checkbox\" data-x=\"'+a.id+'\" '+(e?'checked':'')+'> '+esc(a.nombre)+' <span class=\"pill\">'+money(a.precio)+' · '+a.tipo_pago+'</span></label>'+(club?'<div style=\"margin-top:8px;display:'+(e?'block':'none')+'\"><div class=\"muted\" style=\"font-size:12px;margin-bottom:5px\">Días de asistencia (puedes marcar varios)</div><label style=\"display:inline-block;margin-right:14px\"><input type=\"checkbox\" data-club-day=\"Martes\" '+((e?.club_dias||[]).includes('Martes')?'checked':'')+'> Martes</label><label style=\"display:inline-block;margin-right:14px\"><input type=\"checkbox\" data-club-day=\"Jueves\" '+((e?.club_dias||[]).includes('Jueves')?'checked':'')+'> Jueves</label><label style=\"display:inline-block\"><input type=\"checkbox\" data-club-day=\"Viernes\" '+((e?.club_dias||[]).includes('Viernes')?'checked':'')+'> Viernes</label></div>':'')+(ceas?'<div style=\"margin-top:8px;display:'+(e?'grid':'none')+';gap:8px\"><div><label>Actividad</label><input data-ceas=\"actividad\" value=\"'+esc(e?.ceas_actividad||'')+'\"></div><div><label>Día</label><input data-ceas=\"dia\" value=\"'+esc(e?.ceas_dia||'')+'\" placeholder=\"Miércoles\"></div><div><label>Hora</label><input data-ceas=\"hora\" value=\"'+esc(e?.ceas_hora||'')+'\" placeholder=\"17:00\"></div><div><label>Ubicación / CEAS</label><input data-ceas=\"ubicacion\" value=\"'+esc(e?.ceas_ubicacion||'')+'\"></div></div>':'')+'</div>'}).join('')+'</div><div class=\"right\"><button onclick=\"close()\">Cerrar</button> <button class=\"primary\" onclick=\"saveEnroll(\\\''+uid+'\\\')\">Guardar</button></div>');document.querySelectorAll('#eb input[data-x]').forEach(b=>b.onchange=()=>{const box=b.closest('.card');const n=D.a.find(x=>x.id===b.dataset.x)?.nombre.trim().toLowerCase();const extra=box.querySelector(n==='club de ocio'?'div:nth-of-type(2)':n==='ceas'?'div:nth-of-type(2)':null);if(extra)extra.style.display=b.checked?(n==='ceas'?'grid':'block'):'none'})}
"""
s,n=re.subn(r'async function enroll\(uid\)\{.*?\}\s*async function saveEnroll\(uid\)\{',enroll+'async function saveEnroll(uid){',s,count=1,flags=re.S)
if n!=1: raise SystemExit('enroll replacement failed')
save="""async function saveEnroll(uid){for(const b of document.querySelectorAll('#eb input[data-x]')){const aid=b.dataset.x,old=D.e.find(e=>e.user_id===uid&&e.activity_id===aid&&e.activa),a=D.a.find(x=>x.id===aid),n=a?.nombre.trim().toLowerCase(),box=b.closest('.card'),payload={};if(n==='club de ocio')payload.club_dias=[...box.querySelectorAll('input[data-club-day]:checked')].map(x=>x.dataset.clubDay);if(n==='ceas'){payload.ceas_actividad=box.querySelector('[data-ceas=actividad]')?.value.trim()||null;payload.ceas_dia=box.querySelector('[data-ceas=dia]')?.value.trim()||null;payload.ceas_hora=box.querySelector('[data-ceas=hora]')?.value.trim()||null;payload.ceas_ubicacion=box.querySelector('[data-ceas=ubicacion]')?.value.trim()||null}if(b.checked&&!old){const z=await db.from('enrollments').insert({user_id:uid,activity_id:aid,fecha_inicio:new Date().toISOString().slice(0,10),precio_snapshot:a.precio,tipo_pago_snapshot:a.tipo_pago,activa:true,...payload}).select().single();if(z.error)return alert(z.error.message);if(a.tipo_pago!=='mensual'){const p=a.tipo_pago==='anual'?new Date().toISOString().slice(0,4):new Date().toISOString().slice(0,10);const c=await db.from('charges').upsert({user_id:uid,activity_id:aid,enrollment_id:z.data.id,fecha_cargo:new Date().toISOString().slice(0,10),periodo:p,tipo_pago:a.tipo_pago,importe:a.precio},{onConflict:'owner_id,user_id,activity_id,periodo,tipo_pago'});if(c.error)return alert(c.error.message)}}if(b.checked&&old){const z=await db.from('enrollments').update(payload).eq('id',old.id);if(z.error)return alert(z.error.message)}if(!b.checked&&old){const z=await db.from('enrollments').update({activa:false,fecha_fin:new Date().toISOString().slice(0,10)}).eq('id',old.id);if(z.error)return alert(z.error.message)}}close();load()}
"""
s,n=re.subn(r'async function saveEnroll\(uid\)\{.*?\}\s*function renderUsers\(\)',save+'function renderUsers()',s,count=1,flags=re.S)
if n!=1: raise SystemExit('save replacement failed')
pdf="""function downloadActivityPdf(aid){const a=D.a.find(x=>x.id===aid),d=pdfDoc();if(!d)return alert('No se ha podido preparar el PDF. Comprueba tu conexión a Internet y recarga la página.');const rows=D.e.filter(e=>e.activity_id===aid&&e.activa).map(e=>{const u=D.u.find(x=>x.id===e.user_id);if(!u)return null;const n=a.nombre.trim().toLowerCase();let extra='';if(n==='club de ocio')extra=(e.club_dias||[]).join(', ');if(n==='ceas')extra=[e.ceas_actividad,e.ceas_dia,e.ceas_hora,e.ceas_ubicacion].filter(Boolean).join(' · ');return [u.nombre,u.unidad_residencia||'Sin indicar',u.centro||'',extra]}).filter(Boolean).sort((x,y)=>x[0].localeCompare(y[0],'es'));const detail=a.nombre.trim().toLowerCase()==='club de ocio'?'Días':a.nombre.trim().toLowerCase()==='ceas'?'Detalles':'';pdfHeader(d,'ACTIVIDAD: '+a.nombre,rows.length+' persona(s)'+(a.lugar?' · '+a.lugar:'')+(a.horario?' · '+a.horario:''));d.autoTable({startY:50,head:[['Usuario','Unidad','Centro',detail]],body:rows,styles:{fontSize:8.5,cellPadding:2.5,textColor:PDF_INK,lineColor:PDF_LINE,lineWidth:.25},headStyles:{fillColor:PDF_BLUE,textColor:[255,255,255],fontSize:8.5,fontStyle:'bold'},alternateRowStyles:{fillColor:PDF_LIGHT},margin:{left:10,right:10,top:50,bottom:22}});pdfFooter(d);d.save('Informe_Actividad_'+pdfSlug(a.nombre)+'_'+pdfDate().replaceAll('/','-')+'.pdf')}
"""
s,n=re.subn(r'function downloadActivityPdf\(aid\)\{.*?\}\s*function userIsIncludedInMonth',pdf+'function userIsIncludedInMonth',s,count=1,flags=re.S)
if n!=1: raise SystemExit('pdf replacement failed')
s=s.replace("d.setFillColor(...PDF_BLUE);d.rect(15,12,28,23,'F');d.setDrawColor(...PDF_TURQ);d.setLineWidth(2.2);d.line(15,29,19,27.5);d.line(19,27.5,23,29);d.line(23,29,27,27);d.line(27,27,31,29);d.line(31,29,35,27.5);d.line(35,27.5,39,29);d.line(39,29,43,27.5);d.setDrawColor(...PDF_TURQ);d.setLineWidth(5);d.line(15,32,43,32);","d.setFillColor(...PDF_BLUE);d.rect(15,12,28,23,'F');d.setFillColor(...PDF_TURQ);d.lines([[3,-1],[3,1],[3,-2],[3,2],[3,-1],[3,1],[4,-1.5]],15,29,1,1,{fill:true,closed:true});d.rect(15,31,28,4,'F');")
s=s.replace("acts.map(a=>a.nombre).join(', ')||'Sin actividades'","acts.map(a=>{const e=D.e.find(z=>z.user_id===u.id&&z.activity_id===a.id&&z.activa),n=a.nombre.trim().toLowerCase();return a.nombre+(n==='club de ocio'&&e?.club_dias?.length?' ('+e.club_dias.join(', ')+')':n==='ceas'?' ('+[e?.ceas_actividad,e?.ceas_dia,e?.ceas_hora,e?.ceas_ubicacion].filter(Boolean).join(' · ')+')':'')}).join(', ')||'Sin actividades'")
p.write_text(s)
